### ISSUE TITLE
Make call to jQuery in demo protocol relative

### ISSUE THREAD

**Issue by adamjohnson** [RamonSmit/Nestable#20]
Jquery is being called like:

```html
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>
```

and should be called like:

```html
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>
```

so that drag and drop works for people viewing the demo over HTTPS:

https://dbushell.github.io/Nestable/

If the demo gets served from the master branch, that line is:

https://github.com/RamonSmit/Nestable/blob/master/index.html#L449

**Comment by adamjohnson** [comment]
Ah, just noticed the demo in your `README.md` is pointing to the unmaintained repo; however, the issue still persists in `index.html`.

Perhaps you could update the gh-pages branch and point the demo link in the `README.md` to your demo?

**Comment by RamonSmit** [comment]
Will take a look into this, Thanks for noticing:)
