### ISSUE TITLE
'dd-nodrag' not working

### ISSUE THREAD

**Issue by webtrix** [RamonSmit/Nestable#31]
I've tried to set "dd-nodrag" to several items, but it just doens't work.

example:

``` html
<ol class="dd-list">
    <li data-id="1" class="dd-item"><div class="dd-handle dd-nodrag">test 1</div></li>
    <li data-id="2" class="dd-item"><div class="dd-handle dd-nodrag">test 2</div></li>
    <li data-id="3" class="dd-item"><div class="dd-handle">test 3</div></li>
    <ol class="dd-list">
        <li data-id="4" class="dd-item"><div class="dd-handle dd-nodrag>test 4</div></li>
        <li data-id="5" class="dd-item"><div class="dd-handle">test 5</div></li>
    </ol>
    <li data-id="6" class="dd-item"><div class="dd-handle">test 6</div></li>    
</ol>
```

I looked into the javascript code, and in the onStartEven method, i think I found a bug.
In the first "if-statement" there is this.

``` javascript
if(!handle.hasClass(list.options.handleClass)) {
```

When I remove the "!" .. it works again.

``` javascript
if(handle.hasClass(list.options.handleClass)) {
```

**Comment by RamonSmit** [comment]
Going to test it :smile:

**Comment by webtrix** [comment]
Have you tested it yet?  Seems to be a very small issue to fix, afaik.

**Comment by RamonSmit** [comment]
@webtrix I'm no js developer.

**Comment by sigra** [comment]
After removing "!" sign my expanding buttons doesn't work.

I just move `noDrag` condition to separate condition. Here is my fix:

```javascript
            var onStartEvent = function(e) {
                var handle = $(e.target);

                if(handle.closest('.' + list.options.noDragClass).length) {
                    return;
                }
                if(!handle.hasClass(list.options.handleClass)) {
                    handle = handle.closest('.' + list.options.handleClass);
                }
                if(!handle.length || list.dragEl || (!hasTouch && e.which !== 1) || (hasTouch && e.touches.length !== 1)) {
                    return;
                }
                e.preventDefault();
                list.dragStart(hasTouch ? e.touches[0] : e);
            };

```

**Comment by RamonSmit** [comment]
Would you mind to make a PR of this? Then I just can include it ^^

**Comment by ignas-x** [comment]
Thank You @sigra for thisfix! I just modified this for my needs that only disabled items are un-draggable. But children (without dd-nodrag) still can be rearranged:

`            var onStartEvent = function(e) {
                var handle = $(e.target);
                if(handle.parent().hasClass(list.options.noDragClass)) {
                    return;
                }                
                if(!handle.hasClass(list.options.handleClass)) {
                    handle = handle.closest('.' + list.options.handleClass);
                }
`

**Comment by lcognat** [comment]
Thank you for your solutions.

@ignas-x could you consider creating a pull-request with your fix ?

**Comment by ignas-x** [comment]
@lcognat sorry, I'm very new here... I created fork and edited .js file. Is this enough, or I have to make some other steps ?

**Comment by buglinjo** [comment]
@ignas-x  I have installed that fix but after that dd-nodrag does not work on child elements like input. 
I have modified `onStartEvent` and now it works.

`var onStartEvent = function(e)
{
                var handle = $(e.target);
                if (!handle.hasClass(list.options.handleClass)) {
                    if (handle.closest('.' + list.options.noDragClass).length) {
                        return;
                    }
                    handle = handle.closest('.' + list.options.handleClass);
                }

                if(handle.closest('.dd-handle').parent().hasClass(list.options.noDragClass)){
                    return;
                }

                if (!handle.length || list.dragEl) {
                    return;
                }

                list.isTouch = /^touch/.test(e.type);
                if (list.isTouch && e.touches.length !== 1) {
                    return;
                }

                e.preventDefault();
                list.dragStart(e.touches ? e.touches[0] : e);
            };`

**Comment by webtrix** [comment]
I actually moved to an vanilla JS drag-and-drop script. This one didn't offer enough flexibility.
