### ISSUE TITLE
Demo page - Github URL

### ISSUE THREAD

**Issue by maartentibau** [RamonSmit/Nestable#32]
Hi, when you go to the demo page the "download on github" link still refers to the old Github page being: https://github.com/dbushell/Nestable

**Comment by RamonSmit** [comment]
I see. Totally my mistake! Will fix this asap.

**Comment by webtrix** [comment]
2 months in.. stil not fixed..

**Comment by RamonSmit** [comment]
@webtrix Be my guest to fix stuff.

**Comment by webtrix** [comment]
I cannot really change a link on the demo page you know...

**Comment by RamonSmit** [comment]
@webtrix I always thought you could in the branch 'gh-pages'?
