### ISSUE TITLE
New release and Bower

### ISSUE THREAD

**Issue by marfurt** [RamonSmit/Nestable#36]
Hi,

Since this project is under active development again, could you please distribute a new release?

The last version (1.2.3) dates back to 27 February and some new features (such as `asNestedSet` method) are not available. It would be useful to get a more recent release available via Bower.

**Comment by RamonSmit** [comment]
@marfurt I will fix this tomorrow. 👍

**Comment by marfurt** [comment]
Perfect, thanks!

**Comment by RamonSmit** [comment]
@marfurt Thanks for the heads up tho :-) I even didn't think about it.
