### ISSUE TITLE
Nestable became draggable?

### ISSUE THREAD

**Issue by jsgspotifi** [RamonSmit/Nestable#40]
Am i the only one experiencing this. This just happened, idk.
It ruined my whole system. The nestable became draggable, i can now drag the panels in which of the objects in it dont functio anymore. What happened? I tried it on different units, still the same results i got. Is this because of the browser or what? I need help pls? T_T

**Comment by jsgspotifi** [comment]
All items in a sortable column become draggable, even in this site http://dbushell.github.io/Nestable/ what happened

**Comment by jsgspotifi** [comment]
I already i tried it on 3 different pcs, same result

**Comment by RamonSmit** [comment]
Well, if the link above does the same as your "system" it must be something on your network that is creeping things up. I can't explain that for you. Did you update the nestable or what?

**Comment by jsgspotifi** [comment]
No i didnt do anything T_T this is what happens  https://youtu.be/QmVmebhOmpg

**Comment by RamonSmit** [comment]
Yes, I see. That is supposed to happen. That "big" list has a parent and children and the children of that list are dragged with the parent. You can disable the nesting. So you cannot drag an entire block.

**Comment by jsgspotifi** [comment]
I didnt notice that one before
Well I dont know if i understand it right, but nesting is one the main function of the thing that im working on, i cant just disable it T_T

**Comment by RamonSmit** [comment]
Well that gigantic block you are dragging, that are nested elements.

**Comment by jsgspotifi** [comment]
Okay then, ill just have to observe and figure this out, hoping that there is really a problem with the network. Thank you so much =)) And im sorry, im kind of new to this.

**Comment by RamonSmit** [comment]
@jsgspotifi Doesn't matter, keep trying to learn new stuff :-)
