### ISSUE TITLE
Drag & Drop doesn't work in Chrome

### ISSUE THREAD

**Issue by Danilqa** [RamonSmit/Nestable#44]
Unfortunately, Drag & Drop function doesn't work in Chrome, but touchscreen works good. ]

**Comment by RamonSmit** [comment]
That's weird, It works on chrome in here. You have jQuery installed and loading the nestable after the jQuery package?

**Comment by Danilqa** [comment]
So, I use example file which I have downloaded from your repository. Yes, I have jQuery and loading the nestable after jQuery package. Drag & Drop in Chrome works on multitiuch only :(

**Comment by RamonSmit** [comment]
That's really weird. I might guess it's something locally blocking the execution. 

Tested again on:
Mac/Windows/Linux, all worked in the latest Google Chrome build

**Comment by Danilqa** [comment]
My friends said me, that in their Google Chrome it works, too. Problem only in my Chrome. Thank you for your replies and for your project:) It really usefull!

**Comment by HakamFostok** [comment]
this is exactly what happens to me "My friends said me, that in their Google Chrome it works, too. Problem only in my Chrome"
