### ISSUE TITLE
Nestable not working on Chrome

### ISSUE THREAD

**Issue by HakamFostok** [RamonSmit/Nestable#50]
I copied the example which you provided in the code tab.
I exactly copy and past the following
1. html
2. javascript code
3. your library (js and css file)

simply 'nestable' is not working on chrome version 55.0.2883.87 m (currently latest version)
-note: the chrome console does NOT give me any errors, it is clean

but it's working on Firefox correctly (version 50.1.0)

Any help. Thanks in Advanced

**Comment by pjona** [comment]
If you have still problem, can you provide the example on https://jsfiddle.net/ ?
Currently I don't see any problem with Nestable on Chrome (Tested on 59.0.3071.109).
