### ISSUE TITLE
I was thinking of a new feature

### ISSUE THREAD

**Issue by Ihabafia** [RamonSmit/Nestable#8]
Hi there,

I was thinking of a new feature, which will make the nestable as levels, what I mean by that (not easy to explain)

lets say that we have 4 levels of lists as follows for example:

Sales Director
Sales Managers
Sales Supervisors
Salesmen
each one of these levels especially 3rd and 4th level, needs to be locked. What I mean is that salesman can be moved from a sales supervisor to another sales supervisor but can't be a sales supervisor or sales manager or sales director so he/she must be locked as a salesman in terms of level, but can jump from a branch to another branch.

Same thing with sales supervisor can be moved with his/her salesmen from a sales manager to another sales manager but can't be promoted to a sales manager and can't become a salesman. AND So On...

Thank you,

P.S.: I am welling to sponsor that feature to make the developer get some support.

**Comment by tablatronix** [comment]
Shouldn't this be done with event hooks? Not sure it needs to be in core.

**Comment by RamonSmit** [comment]
Valid awnser :+1:
